### ISSUE TITLE
Pin package version?

### ISSUE THREAD

**Issue by hsm207** [ZacharyHimmelberger/image-classification-for-technical-indicators#4]
Should we pin the version of the packages we installed in the [dockerfile](https://github.com/ZacharyHimmelberger/image-classification-for-technical-indicators/blob/fc0154ffd03db65dd191c970e67c20e803301354/.devcontainer/Dockerfile#L23-L36)?

**Comment by ZacharyHimmelberger** [comment]
Yes, good idea. Can you make the change for one package in your open PR so I can see how, then I will complete the other packages?

**Comment by hsm207** [comment]
done!

**Comment by ZacharyHimmelberger** [comment]
The library versions were pinned to the dockerfile.
